// app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "bootstrap/dist/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import AosInit from "./AOS";
import "aos/dist/aos.css";
import BackToTop from "./Home/BackToTop"

// <-- DIRECT import of client component (allowed)
import FloatingButton from "./Home/FloatingButton";

const poppins = localFont({
  src: [
    { path: "../public/fonts/Poppins-Light.ttf", weight: "300", style: "normal" },
    { path: "../public/fonts/Poppins-Medium.ttf", weight: "500", style: "normal" },
    { path: "../public/fonts/Poppins-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <AosInit />
        {children}

        <BackToTop/>

        {/* Always-visible vertical floating button (client component) */}
         <FloatingButton /> 
      </body>
    </html>
  );
}
